/*==============================================================================
 OLIST E-COMMERCE ANALYTICS PROJECT
 File: 03_sales_analysis.sql

 Purpose:
 Analyze sales performance across time, product categories, customers,
 and order values to identify revenue trends and business opportunities.

 Author: Sania
==============================================================================*/


/*==============================================================================
Query 1
Business Question:
What is the total revenue generated by the marketplace?
==============================================================================*/

SELECT
    ROUND(SUM(payment_value),2) AS total_revenue
FROM payments;



/*==============================================================================
Query 2
Business Question:
What is the average order value?
==============================================================================*/

SELECT
    ROUND(AVG(payment_value),2) AS average_order_value
FROM payments;



/*==============================================================================
Query 3
Business Question:
How much revenue was generated each month?
==============================================================================*/

SELECT
    strftime('%Y-%m', o.order_purchase_timestamp) AS purchase_month,
    ROUND(SUM(p.payment_value),2) AS monthly_revenue
FROM orders o
JOIN payments p
ON o.order_id = p.order_id
GROUP BY purchase_month
ORDER BY purchase_month;



/*==============================================================================
Query 4
Business Question:
How many orders were placed each month?
==============================================================================*/

SELECT
    strftime('%Y-%m', order_purchase_timestamp) AS purchase_month,
    COUNT(*) AS total_orders
FROM orders
GROUP BY purchase_month
ORDER BY purchase_month;



/*==============================================================================
Query 5
Business Question:
What is the average order value for each month?
==============================================================================*/

SELECT
    strftime('%Y-%m', o.order_purchase_timestamp) AS purchase_month,
    ROUND(AVG(p.payment_value),2) AS average_order_value
FROM orders o
JOIN payments p
ON o.order_id = p.order_id
GROUP BY purchase_month
ORDER BY purchase_month;



/*==============================================================================
Query 6
Business Question:
How much revenue was generated by each order status?
==============================================================================*/

SELECT
    o.order_status,
    ROUND(SUM(p.payment_value),2) AS revenue
FROM orders o
JOIN payments p
ON o.order_id = p.order_id
GROUP BY o.order_status
ORDER BY revenue DESC;



/*==============================================================================
Query 7
Business Question:
Which customer states generated the highest revenue?
==============================================================================*/

SELECT
    c.customer_state,
    ROUND(SUM(p.payment_value),2) AS revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_state
ORDER BY revenue DESC;



/*==============================================================================
Query 8
Business Question:
Which product categories generated the highest revenue?
==============================================================================*/

SELECT
    pct.product_category_name_english AS category,
    ROUND(SUM(oi.price),2) AS revenue
FROM order_items oi
JOIN products pr
ON oi.product_id = pr.product_id
JOIN category_translation pct
ON pr.product_category_name = pct.product_category_name
GROUP BY category
ORDER BY revenue DESC;



/*==============================================================================
Query 9
Business Question:
Which product categories sold the highest number of items?
==============================================================================*/

SELECT
    pct.product_category_name_english AS category,
    COUNT(*) AS products_sold
FROM order_items oi
JOIN products pr
ON oi.product_id = pr.product_id
JOIN category_translation pct
ON pr.product_category_name = pct.product_category_name
GROUP BY category
ORDER BY products_sold DESC;



/*==============================================================================
Query 10
Business Question:
Which individual products generated the highest revenue?
==============================================================================*/

SELECT
    product_id,
    ROUND(SUM(price),2) AS revenue
FROM order_items
GROUP BY product_id
ORDER BY revenue DESC
LIMIT 20;



/*==============================================================================
Query 11
Business Question:
Which orders had the highest payment values?
==============================================================================*/

SELECT
    order_id,
    ROUND(SUM(payment_value),2) AS order_value
FROM payments
GROUP BY order_id
ORDER BY order_value DESC
LIMIT 20;



/*==============================================================================
Query 12
Business Question:
What is the average product price for each category?
==============================================================================*/

SELECT
    pct.product_category_name_english AS category,
    ROUND(AVG(oi.price),2) AS average_price
FROM order_items oi
JOIN products pr
ON oi.product_id = pr.product_id
JOIN category_translation pct
ON pr.product_category_name = pct.product_category_name
GROUP BY category
ORDER BY average_price DESC;



/*==============================================================================
Query 13
Business Question:
Which weekdays generate the highest revenue?
==============================================================================*/

SELECT

    CASE strftime('%w', o.order_purchase_timestamp)
        WHEN '0' THEN 'Sunday'
        WHEN '1' THEN 'Monday'
        WHEN '2' THEN 'Tuesday'
        WHEN '3' THEN 'Wednesday'
        WHEN '4' THEN 'Thursday'
        WHEN '5' THEN 'Friday'
        WHEN '6' THEN 'Saturday'
    END AS weekday,

    ROUND(SUM(p.payment_value),2) AS revenue

FROM orders o
JOIN payments p
ON o.order_id = p.order_id

GROUP BY weekday

ORDER BY revenue DESC;



/*==============================================================================
Query 14
Business Question:
What are the top 10 highest-priced products sold?
==============================================================================*/

SELECT
    product_id,
    price
FROM order_items
ORDER BY price DESC
LIMIT 10;



/*==============================================================================
Query 15
Business Question:
What is the average freight cost across all orders?
==============================================================================*/

SELECT
    ROUND(AVG(freight_value),2) AS average_freight_cost
FROM order_items;



/*==============================================================================
End of File
==============================================================================*/